### ISSUE TITLE
table.h missing

### ISSUE THREAD

**Issue by pklaus** [jed1/smrtlink#1]
It seems like your implementation for the lookup table is missing in the repository:

    [philipp@lion smrtlink]$ make
    g++ -g -c -std=c++14 src/jsonNode.cpp -o bin/jsonNode.o
    g++ -g -c -std=c++14 src/bytes.cpp -o bin/bytes.o
    g++ -g -c -std=c++14 src/Switch.cpp -o bin/Switch.o
    In file included from src/Switch.cpp:11:0:
    src/Lookup.h:8:19: fatal error: table.h: No such file or directory
    compilation terminated.
    Makefile:22: recipe for target 'bin/Switch.o' failed
    make: *** [bin/Switch.o] Error 1

**Comment by jed1** [comment]
Fixed.
Thank you.
